name: CI
on: push
jobs:
  test:
    name: Lint & Typecheck
    runs-on: ubuntu-latest

    # Start a Postgres instance, which is used during tests
    # services:
    #   postgres:
    #     image: postgres
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: postgres
    #     ports:
    #       - 5432:5432
    #     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    # env:
    #   # This needs to match the POSTGRES_* env variables set in the Postgres service above
    #   DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Copy example env
        run: cp .env.example .env

      - name: Generate
        run: npm run generate

      # - name: Migrate the CI database
      #   run: npm run prisma:migrate

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      # - name: Tests (Jest)
      #   run: npm run test

      # - name: End-to-end tests (Cypress)
      #   uses: cypress-io/github-action@v2
      #   with:
      #     install-command: yarn --frozen-lockfile --silent
      #     build: yarn build
      #     start: yarn start:ci
      #     wait-on: http://localhost:3000
